//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CavityQuantities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vCavityMatrixModel
    {
        public int nbattrid { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public int cavityid { get; set; }
        public string cavityname { get; set; }
        public Nullable<bool> isautorouterfeature { get; set; }
        public string cseries { get; set; }
        public Nullable<int> isqqfeature { get; set; }
        public int modelid { get; set; }
        public string partno { get; set; }
    }
}
