//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CavityQuantities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSA_Sales
    {
        public string RecordID { get; set; }
        public string Record_Type { get; set; }
        public Nullable<System.DateTime> Inv_So_Date { get; set; }
        public string Cust_Nbr { get; set; }
        public string Part_Nbr { get; set; }
        public string Long_Part_Nbr { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Ext_List_Price { get; set; }
        public Nullable<decimal> Part_Discount { get; set; }
        public Nullable<decimal> Sales { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> Gross_Margin_Dollars { get; set; }
        public string Quote { get; set; }
        public string SONbr { get; set; }
        public string SOLine { get; set; }
        public string Del_Nbr { get; set; }
        public string Inv_So_Nbr { get; set; }
        public string Inv_Line_Nbr { get; set; }
        public string Ship_To_Addr_Code { get; set; }
        public Nullable<System.DateTime> Customer_Req_Date { get; set; }
        public string Invoice_Type { get; set; }
        public string Inventory_Type { get; set; }
        public string Sales_Code { get; set; }
        public string Price_Grp_Code { get; set; }
        public string Division_Code { get; set; }
    }
}
